### ISSUE TITLE
Can’t login

### ISSUE THREAD

**Issue by Lalaleah** [itsjavi/supereffective-issues#53]
I’m trying to login via google as I already have an account but it’s saying it’s ‘depreciated’ and asking me to enter an email to send a login link - I have tried with 2 different emails (the google one that is the same as the google account I initially tried to login with, and a Hotmail one) and I’ve not received a link for either.

**Comment by itsjavi** [comment]
We are currently experiencing issues with our Sign In system.

New Log-ins and Sign-ups are currently disabled until we investigate and fix the issue.
Sorry for the inconveniences.

**Comment by itsjavi** [comment]
fixed
